name = "will-it-rain"
main = "src/index.ts"
compatibility_date = "2025-03-01"

[triggers]
crons = ["*/10 * * * *"]

[[kv_namespaces]]
binding = "DEVICES"
id = "142615e17bc84dc7adbd9e64d0b29410"

[observability]
enabled = true
